# Objective : Learning the process of identifying mostsimilar users using standardized ratings
## Problem : Given below, the raw scores for 5 users.x
### User-1 : 7,6,7,4,5,4
### User-2 : 6,7,?,4,3,4
### User-3 : ?,3,3,1,1,?
### User-4 : 1,2,2,3,3,4
### User-5 : 1,?,1,2,3,3
### a. Obtain the standardized ratings
### b. Find the top-2 most similar users for user 3
### c. Estimate r(3,6)

In [1]:
#Step-1: Computing Standardized Ratings


In [2]:
import numpy as np


In [3]:
raw_score=np.array([7,6,7,4,5,4])
mn=np.mean(raw_score)
print(mn)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt(psd*psd)
sd=np.sqrt((n/(n-1)*psd*psd))
sdsc1=(raw_score-mn)/sd
sdsc1


5.5


array([ 1.08821438,  0.36273813,  1.08821438, -1.08821438, -0.36273813,
       -1.08821438])

In [4]:
raw_score=np.array([6,7,4,3,4])
mn=np.mean(raw_score)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt((n/(n-1)*psd*psd))
sdsc2=(raw_score-mn)/sd
sdsc2


array([ 0.73029674,  1.33887736, -0.4868645 , -1.09544512, -0.4868645 ])

In [5]:
raw_score=np.array([3,3,1,1])
mn=np.mean(raw_score)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt((n/(n-1)*psd*psd))
sdsc3=(raw_score-mn)/sd
sdsc3


array([ 0.8660254,  0.8660254, -0.8660254, -0.8660254])

In [6]:
raw_score=np.array([1,2,2,3,3,4])
mn=np.mean(raw_score)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt((n/(n-1)*psd*psd))
sdsc4=(raw_score-mn)/sd
sdsc4


array([-1.43019388, -0.47673129, -0.47673129,  0.47673129,  0.47673129,
        1.43019388])

In [7]:
raw_score=np.array([1,1,2,3,3])
mn=np.mean(raw_score)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt((n/(n-1)*psd*psd))
sdsc5=(raw_score-mn)/sd
sdsc5


array([-1., -1.,  0.,  1.,  1.])

In [8]:
#Step-2 : Computing similarities between user-3 and


In [9]:
r1= np.array([0.36273813,  1.08821438, -1.08821438, -0.36273813])
r2=np.array([ 0.8660254,  0.8660254, -0.8660254, -0.8660254])
nr=sum(r1*r2)
dr=np.sqrt(sum(r1*r1)*sum(r2*r2))
s_3_1=nr/dr
print(s_3_1)


0.8944271922327987


In [10]:
r1= np.array([ 1.33887736, -0.4868645 , -1.09544512])
r2=np.array([ 0.8660254,  -0.8660254, -0.8660254])
nr=sum(r1*r2)
dr=np.sqrt(sum(r1*r1)*sum(r2*r2))
s_3_2=nr/dr
print(s_3_2)


0.9384742654090402


In [11]:
r1=np.array([-0.47673129, -0.47673129,  0.47673129,  0.47673129])
r2=np.array([0.8660254, 0.8660254,  -0.8660254, -0.8660254])
nr=sum(r1*r2)
dr=np.sqrt(sum(r1*r1)*sum(r2*r2))
s_3_4=nr/dr
print(s_3_4)


-1.0


In [12]:
r1=np.array([ 0.8660254, -0.8660254, -0.8660254])
r2=np.array([-1,0,1])
nr=sum(r1*r2)
dr=np.sqrt(sum(r1*r1)*sum(r2*r2))
s_3_5=nr/dr
print(s_3_5)


-0.816496580927726


## The top-2 most similar users for user 3 are 1 and 2 whose standarized-ratings for item 6 are -0.4868645 and -1.08821438

In [13]:
import numpy as np
raw_score=np.array([3,3,1,1])
mu_3=np.mean(raw_score)
psd=np.std(raw_score)
n=len(raw_score)
sd=np.sqrt(psd*psd)
sd=np.sqrt((n/(n-1)*psd*psd))
r36_hat=mu_3+sd*((s_3_1*sdsc1[5]+s_3_2*sdsc2[4])/(s_3_1+s_3_2))
print("Estimated rating is ",r36_hat)


Estimated rating is  1.0989712183326192


# Conclusion: r(3,6) is 1.09